INSERT INTO Activos (Nombre, Descripcion, FechaAdquisicion, Estado) VALUES
('Silla Ejecutiva', 'Silla acolchonada con soporte lumbar ajustable', '2025-03-01', 'Activo'),
('Laptop Dell XPS 15', 'Laptop de alto rendimiento para tareas de diseño', '2023-05-10', 'En Mantenimiento'),
('Impresora HP LaserJet Pro', 'Impresora láser monocromática para oficina', '2022-08-15', 'Inactivo'),
('Monitor Samsung 24"', 'Monitor LED de 24 pulgadas para estación de trabajo', '2023-03-01', 'Activo'),
('Proyector Epson XGA', 'Proyector de 2000 lúmenes para presentaciones', '2021-11-25', 'En Mantenimiento'),
('Mouse Logitech MX Master', 'Mouse ergonómico inalámbrico con múltiples botones', '2023-02-10', 'Activo'),
('Teclado Mecánico Corsair', 'Teclado con retroiluminación RGB', '2022-12-05', 'Activo'),
('Servidor Dell PowerEdge', 'Servidor empresarial para respaldo de datos', '2021-07-20', 'Activo'),
('Cámara Web Logitech C920', 'Cámara HD para videollamadas y grabación', '2023-01-18', 'Activo'),
('Router Cisco RV260W', 'Router empresarial con VPN y firewall', '2022-05-22', 'Inactivo'),
('Estabilizador de Voltaje APC', 'Estabilizador para proteger equipos eléctricos', '2020-10-30', 'Inactivo'),
('Disco Duro Externo Seagate 2TB', 'Almacenamiento portátil de respaldo', '2023-03-15', 'Activo'),
('Laptop HP Pavilion', 'Laptop para tareas administrativas', '2023-06-01', 'Activo'),
('Silla Ergonómica Herman Miller', 'Silla ergonómica con diseño profesional', '2022-09-12', 'Activo'),
('Bocinas Bose SoundLink', 'Bocinas inalámbricas con sonido envolvente', '2023-01-25', 'Activo'),
('Escáner Epson Perfection', 'Escáner para documentos y fotografías', '2021-02-18', 'En Mantenimiento'),
('Cargador Anker 20W', 'Cargador rápido USB-C para móviles', '2023-07-05', 'Activo'),
('Teléfono IP Cisco', 'Teléfono empresarial VoIP', '2022-06-30', 'Activo'),
('Cámara de Seguridad Arlo Pro', 'Cámara para monitoreo remoto con visión nocturna', '2022-11-10', 'Activo'),
('Dispositivo de Red Ubiquiti UniFi', 'Access point para redes empresariales', '2021-08-25', 'Inactivo'),
('Router Netgear Nighthawk', 'Router Wi-Fi de alto rendimiento para oficina', '2023-04-12', 'Activo'),
('Computadora ASUS', 'Computadora de escritorio para oficina', '2025-03-01', 'En Mantenimiento'),
('Escritorio de Oficina L-Shape', 'Escritorio en forma de L con almacenamiento', '2023-02-20', 'Activo'),
('Multifuncional Brother MFC-L2710DW', 'Impresora, escáner y fax todo en uno', '2024-01-05', 'Activo'),
('Aire Acondicionado LG Inverter', 'Sistema de aire eficiente para oficinas', '2022-12-15', 'En Mantenimiento'),
('Reloj Digital de Pared', 'Reloj con hora y temperatura para ambientes laborales', '2023-07-01', 'Activo'),
('Archivador Metálico de 4 Gavetas', 'Archivador con cerradura para documentos físicos', '2021-09-10', 'Activo'),
('Paneles Divisorios de Oficina', 'Paneles modulares para separación de espacios', '2022-08-08', 'Activo'),
('Cafetera Industrial Nespresso', 'Cafetera para uso frecuente en entornos laborales', '2024-04-02', 'Activo'),
('Pantalla Interactiva Smart Board', 'Pizarra digital táctil para presentaciones', '2023-11-28', 'Activo');
