//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ControldeActivos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivoArchivos
    {
        public int Id { get; set; }
        public int IdActivo { get; set; }
        public string NombreArchivo { get; set; }
        public string TipoArchivo { get; set; }
        public string ExtArchivo { get; set; }
        public int TamanoArchivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string RutaArchivo { get; set; }
    
        public virtual Activos Activos { get; set; }
    }
}
