//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ControldeActivos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activos
    {
        public Activos()
        {
            this.ActivoArchivos = new HashSet<ActivoArchivos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaAdquisicion { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<ActivoArchivos> ActivoArchivos { get; set; }
    }
}
